/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package team.ytk.stream;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void test() {
        List<Integer> array = new ArrayList<>() {
            {
                add(11);
                add(22);
                add(33);
            }
        };

        Stream
            .from(array.stream())
            .forEach(
                item -> {
                    System.out.format(
                        "index:%s, value:%s, size:%s, list:%s\n",
                        item.index,
                        item.value,
                        item.size,
                        item.list
                    );
                }
            );
    }
}
